# ruff: noqa: E501

from __future__ import annotations

from kalshi_predictor.live_readiness.contracts import (
    CONTROL_CATALOG_VERSION,
    SEVERITY_CRITICAL,
    SEVERITY_HIGH,
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
    ControlDefinition,
)


def _control(
    family: str,
    prefix: str,
    number: str,
    severity: str,
    title: str,
    criterion: str | None = None,
    evidence: str | None = None,
) -> ControlDefinition:
    control_id = f"{prefix}-{number}"
    return ControlDefinition(
        control_id=control_id,
        family=family,
        severity=severity,
        title=title,
        acceptance_criterion=criterion or f"{title} has current, reviewable evidence.",
        evidence_required=evidence or "Immutable evidence artifact, owner, timestamp, and hash.",
    )


CONTROL_CATALOG: tuple[ControlDefinition, ...] = (
    _control(
        "Review Integrity",
        "REV",
        "001",
        SEVERITY_CRITICAL,
        "Exact build, config, model, account, and stage scope is frozen.",
    ),
    _control("Review Integrity", "REV", "002", SEVERITY_CRITICAL, "Evidence manifest is immutable."),
    _control("Review Integrity", "REV", "003", SEVERITY_HIGH, "Conflicting evidence is resolved."),
    _control("Review Integrity", "REV", "004", SEVERITY_HIGH, "Evidence freshness policy is met."),
    _control(
        "Review Integrity",
        "REV",
        "005",
        SEVERITY_CRITICAL,
        "Decision cannot be changed without new review.",
    ),
    _control("Review Integrity", "REV", "006", SEVERITY_MEDIUM, "Review report is reproducible."),
    _control("Governance", "GOV", "001", SEVERITY_CRITICAL, "Account owner approves launch scope."),
    _control("Governance", "GOV", "002", SEVERITY_CRITICAL, "Risk owner approves hard limits."),
    _control("Governance", "GOV", "003", SEVERITY_HIGH, "Operator on-call owner is assigned."),
    _control("Governance", "GOV", "004", SEVERITY_CRITICAL, "Kill authority is documented."),
    _control("Governance", "GOV", "005", SEVERITY_HIGH, "Change freeze window is defined."),
    _control("Governance", "GOV", "006", SEVERITY_MEDIUM, "Post-launch review cadence is set."),
    _control("Legal And Eligibility", "LEG", "001", SEVERITY_CRITICAL, "Account is eligible for live trading."),
    _control("Legal And Eligibility", "LEG", "002", SEVERITY_HIGH, "Jurisdiction and product rules are reviewed."),
    _control("Legal And Eligibility", "LEG", "003", SEVERITY_HIGH, "Exchange terms and API rules are reviewed."),
    _control("Legal And Eligibility", "LEG", "004", SEVERITY_MEDIUM, "Tax and recordkeeping owner is named."),
    _control("Legal And Eligibility", "LEG", "005", SEVERITY_HIGH, "Funding source and loss tolerance are approved."),
    _control("Legal And Eligibility", "LEG", "006", SEVERITY_CRITICAL, "No prohibited automated behavior is enabled."),
    _control("Software Delivery", "SDLC", "001", SEVERITY_CRITICAL, "Release artifact hash is pinned."),
    _control("Software Delivery", "SDLC", "002", SEVERITY_HIGH, "Dependency lockfile is reviewed."),
    _control("Software Delivery", "SDLC", "003", SEVERITY_HIGH, "Test suite passes for release artifact."),
    _control("Software Delivery", "SDLC", "004", SEVERITY_CRITICAL, "Migrations are tested and reversible."),
    _control("Software Delivery", "SDLC", "005", SEVERITY_MEDIUM, "Feature flags default to fail closed."),
    _control("Software Delivery", "SDLC", "006", SEVERITY_CRITICAL, "Live write path has startup guard."),
    _control("Model Validation", "MOD", "001", SEVERITY_HIGH, "Model versions are pinned."),
    _control("Model Validation", "MOD", "002", SEVERITY_CRITICAL, "Backtest and paper evidence support launch."),
    _control("Model Validation", "MOD", "003", SEVERITY_HIGH, "Calibration evidence is acceptable."),
    _control("Model Validation", "MOD", "004", SEVERITY_HIGH, "Segment performance is reviewed."),
    _control("Model Validation", "MOD", "005", SEVERITY_MEDIUM, "Model drift monitors exist."),
    _control("Model Validation", "MOD", "006", SEVERITY_CRITICAL, "No unvalidated model can place risk."),
    _control("Model Validation", "MOD", "007", SEVERITY_HIGH, "Model fallback behavior is deterministic."),
    _control("Model Validation", "MOD", "008", SEVERITY_MEDIUM, "Feature provenance is documented."),
    _control("Model Validation", "MOD", "009", SEVERITY_HIGH, "Learning mode cannot bypass validation."),
    _control("Model Validation", "MOD", "010", SEVERITY_CRITICAL, "Final Phase 3N risk authority is preserved."),
    _control("Data Quality", "DAT", "001", SEVERITY_CRITICAL, "Market data source is authenticated and current."),
    _control("Data Quality", "DAT", "002", SEVERITY_CRITICAL, "Order book freshness gate exists."),
    _control("Data Quality", "DAT", "003", SEVERITY_HIGH, "Forecast inputs are point-in-time safe."),
    _control("Data Quality", "DAT", "004", SEVERITY_CRITICAL, "Stale or missing price blocks new risk."),
    _control("Data Quality", "DAT", "005", SEVERITY_HIGH, "Settlement data reconciliation is available."),
    _control("Data Quality", "DAT", "006", SEVERITY_MEDIUM, "External feature ingestion has quality checks."),
    _control("Data Quality", "DAT", "007", SEVERITY_HIGH, "Clock and timezone handling is verified."),
    _control("Data Quality", "DAT", "008", SEVERITY_MEDIUM, "Data lineage is retained."),
    _control("Risk", "RSK", "001", SEVERITY_CRITICAL, "Global loss limit is enforced."),
    _control("Risk", "RSK", "002", SEVERITY_CRITICAL, "Per-market risk cap is enforced."),
    _control("Risk", "RSK", "003", SEVERITY_CRITICAL, "Per-order size cap is enforced."),
    _control("Risk", "RSK", "004", SEVERITY_CRITICAL, "Daily loss kill switch is enforced."),
    _control("Risk", "RSK", "005", SEVERITY_CRITICAL, "Position limit prevents over-positioning."),
    _control("Risk", "RSK", "006", SEVERITY_HIGH, "Liquidity and spread gates are enforced."),
    _control("Risk", "RSK", "007", SEVERITY_HIGH, "Correlation concentration controls exist."),
    _control("Risk", "RSK", "008", SEVERITY_CRITICAL, "Phase 3N cannot be bypassed."),
    _control("Risk", "RSK", "009", SEVERITY_CRITICAL, "Risk cap increases require new approval."),
    _control("Risk", "RSK", "010", SEVERITY_HIGH, "Paper/live state separation is preserved."),
    _control("Execution", "EXE", "001", SEVERITY_CRITICAL, "Live order creation is guarded by certificate."),
    _control("Execution", "EXE", "002", SEVERITY_CRITICAL, "Invalid certificate allows cancel-only mode."),
    _control("Execution", "EXE", "003", SEVERITY_HIGH, "Order idempotency is enforced."),
    _control("Execution", "EXE", "004", SEVERITY_HIGH, "Order retry policy is bounded."),
    _control("Execution", "EXE", "005", SEVERITY_CRITICAL, "Demo and paper execution cannot arm live writes."),
    _control("Execution", "EXE", "006", SEVERITY_CRITICAL, "Order side and price validation is enforced."),
    _control("Execution", "EXE", "007", SEVERITY_HIGH, "Partial fill and rejection handling is tested."),
    _control("Execution", "EXE", "008", SEVERITY_CRITICAL, "No autonomous live launch flag exists."),
    _control("Execution", "EXE", "009", SEVERITY_CRITICAL, "Cancel and flatten controls are tested."),
    _control("Execution", "EXE", "010", SEVERITY_CRITICAL, "Exchange write credentials are not exposed to UI."),
    _control("Execution", "EXE", "011", SEVERITY_CRITICAL, "WebSocket disconnect blocks new risk."),
    _control("Execution", "EXE", "012", SEVERITY_CRITICAL, "Production endpoint use requires approval."),
    _control("Reconciliation", "REC", "001", SEVERITY_HIGH, "Positions reconcile to account state."),
    _control("Reconciliation", "REC", "002", SEVERITY_CRITICAL, "Cash and buying power are checked."),
    _control("Reconciliation", "REC", "003", SEVERITY_HIGH, "Open orders reconcile before new risk."),
    _control("Reconciliation", "REC", "004", SEVERITY_MEDIUM, "Settlement mismatch workflow exists."),
    _control("Reconciliation", "REC", "005", SEVERITY_CRITICAL, "Unknown position state blocks new risk."),
    _control("Reconciliation", "REC", "006", SEVERITY_HIGH, "PnL calculation is independently checked."),
    _control("Reconciliation", "REC", "007", SEVERITY_MEDIUM, "Corporate or exchange adjustment handling exists."),
    _control("Reconciliation", "REC", "008", SEVERITY_HIGH, "Manual correction workflow is controlled."),
    _control("Security", "SEC", "001", SEVERITY_CRITICAL, "Live secrets are not stored in code or reports."),
    _control("Security", "SEC", "002", SEVERITY_CRITICAL, "Private key handling is isolated."),
    _control("Security", "SEC", "003", SEVERITY_CRITICAL, "Least privilege credentials are used."),
    _control("Security", "SEC", "004", SEVERITY_HIGH, "Secret rotation process is documented."),
    _control("Security", "SEC", "005", SEVERITY_HIGH, "Access logging covers live write paths."),
    _control("Security", "SEC", "006", SEVERITY_HIGH, "Dependency and vulnerability scan is reviewed."),
    _control("Security", "SEC", "007", SEVERITY_MEDIUM, "Workstation hardening is documented."),
    _control("Security", "SEC", "008", SEVERITY_HIGH, "Browser UI cannot access credentials."),
    _control("Security", "SEC", "009", SEVERITY_MEDIUM, "Backup encryption is verified."),
    _control("Resilience", "RES", "001", SEVERITY_CRITICAL, "Kill switch is tested."),
    _control("Resilience", "RES", "002", SEVERITY_CRITICAL, "Database corruption recovery is tested."),
    _control("Resilience", "RES", "003", SEVERITY_HIGH, "Network failure behavior is tested."),
    _control("Resilience", "RES", "004", SEVERITY_CRITICAL, "Database locked state blocks new risk."),
    _control("Resilience", "RES", "005", SEVERITY_HIGH, "Scheduler restart behavior is safe."),
    _control("Resilience", "RES", "006", SEVERITY_CRITICAL, "Malformed config fails closed."),
    _control("Resilience", "RES", "007", SEVERITY_HIGH, "Incident response runbook is current."),
    _control("Resilience", "RES", "008", SEVERITY_CRITICAL, "Certificate revocation takes effect."),
    _control("Resilience", "RES", "009", SEVERITY_CRITICAL, "Startup without certificate blocks new risk."),
    _control("Operations", "OPS", "001", SEVERITY_HIGH, "Dashboards show live readiness status."),
    _control("Operations", "OPS", "002", SEVERITY_HIGH, "Alerts cover risk, data, and execution failures."),
    _control("Operations", "OPS", "003", SEVERITY_MEDIUM, "Operator handoff notes exist."),
    _control("Operations", "OPS", "004", SEVERITY_MEDIUM, "Morning review report is defined."),
    _control("Operations", "OPS", "005", SEVERITY_HIGH, "Log retention policy is defined."),
    _control("Operations", "OPS", "006", SEVERITY_MEDIUM, "Clock skew monitoring exists."),
    _control("Operations", "OPS", "007", SEVERITY_MEDIUM, "Capacity and rate-limit checks are reviewed."),
    _control("Operations", "OPS", "008", SEVERITY_LOW, "UI explains inactive readiness controls."),
    _control("Operations", "OPS", "009", SEVERITY_MEDIUM, "Manual override ledger exists."),
    _control("Operations", "OPS", "010", SEVERITY_HIGH, "Operator can confirm cancel-only state."),
    _control("Audit", "AUD", "001", SEVERITY_HIGH, "Append-only readiness records are persisted."),
    _control("Audit", "AUD", "002", SEVERITY_HIGH, "Decision lineage references evidence hashes."),
    _control("Audit", "AUD", "003", SEVERITY_MEDIUM, "Report export is reproducible."),
    _control("Audit", "AUD", "004", SEVERITY_CRITICAL, "Live write attempts are audit logged."),
    _control("Audit", "AUD", "005", SEVERITY_HIGH, "Certificate lifecycle events are logged."),
    _control("Audit", "AUD", "006", SEVERITY_CRITICAL, "Risk overrides are impossible or logged."),
    _control("Audit", "AUD", "007", SEVERITY_MEDIUM, "Evidence retention owner is assigned."),
    _control("Human Readiness", "HUM", "001", SEVERITY_HIGH, "Launch owner is available."),
    _control("Human Readiness", "HUM", "002", SEVERITY_CRITICAL, "Go/no-go meeting is complete."),
    _control("Human Readiness", "HUM", "003", SEVERITY_HIGH, "Rollback drill is understood."),
    _control("Human Readiness", "HUM", "004", SEVERITY_MEDIUM, "Known issues are acknowledged."),
    _control("Human Readiness", "HUM", "005", SEVERITY_CRITICAL, "Two-person approval is recorded."),
    _control("Human Readiness", "HUM", "006", SEVERITY_CRITICAL, "Real capital risk amount is approved."),
    _control("Human Readiness", "HUM", "007", SEVERITY_CRITICAL, "Operator confirms no autonomous launch."),
)

CONTROL_BY_ID = {control.control_id: control for control in CONTROL_CATALOG}


def catalog_summary() -> dict[str, int | str]:
    return {
        "catalog_version": CONTROL_CATALOG_VERSION,
        "control_count": len(CONTROL_CATALOG),
        "critical_count": sum(1 for control in CONTROL_CATALOG if control.severity == SEVERITY_CRITICAL),
        "high_count": sum(1 for control in CONTROL_CATALOG if control.severity == SEVERITY_HIGH),
        "medium_count": sum(1 for control in CONTROL_CATALOG if control.severity == SEVERITY_MEDIUM),
        "low_count": sum(1 for control in CONTROL_CATALOG if control.severity == SEVERITY_LOW),
    }
